# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Projects/SOC_Projects/UART_GPIO_Zedboard/UART_GPIO_Zedboard.srcs/sources_1/bd/System/ip/System_xbar_0/System_xbar_0.xci
# IP: The module: 'System_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/SOC_Projects/UART_GPIO_Zedboard/UART_GPIO_Zedboard.gen/sources_1/bd/System/ip/System_xbar_0/System_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Projects/SOC_Projects/UART_GPIO_Zedboard/UART_GPIO_Zedboard.srcs/sources_1/bd/System/ip/System_xbar_0/System_xbar_0.xci
# IP: The module: 'System_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/SOC_Projects/UART_GPIO_Zedboard/UART_GPIO_Zedboard.gen/sources_1/bd/System/ip/System_xbar_0/System_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
